### ISSUE TITLE
Release 0.3.1?

### ISSUE THREAD

**Issue by afgane** [galaxyproject/ephemeris#19]
Could the next minor release be created? It would make simplify the tool installation process for the Galaxy Standalone VM currently being worked on.

**Comment by jmchilton** [comment]
I called it 0.4.0 since I save the last dot for bug fixes in my other projects. Should be available here now https://pypi.python.org/pypi/ephemeris. I need to improve the HISTORY.rst generation process to be on par with planemo but I added some stubs without links by hand for now. Let me know if there is anything else you need.

**Comment by afgane** [comment]
Thanks.
